### ISSUE TITLE
Connection gets the event "disconnected", but sender link's is_open()  returns true.

### ISSUE THREAD

**Issue by amarzavery** [amqp/rhea#101]
- More info can be found over [here](https://github.com/Azure/azure-event-hubs-node/issues/96#issuecomment-405545690).

@grs - What are your thoughts on this?

**Comment by amarzavery** [comment]
Couple of things:
1. Looks like the `EventContext` type definition should also have an optional `error` property. In the `_disconnected()` method, [`disconnect_ctxt` object's `error` property is set if error is present](https://github.com/amqp/rhea/blob/master/lib/connection.js#L485). The `disconnect_ctxt` object is then passed to `this._context()` and it's output is returned as the EventContext for "disconnected" event. This means that the context can have an optional error property.
    1. It looks like the `error` property can either be a `string` or an `Error` object. `if (error) { disconnect_ctxt.error = error.error || error.message;  }`. 
        1. I am not sure if `error.error` is an AMQP error or a normal Javascript Error. Any thoughts?
        2. I feel sending a standard Error object always is a better option rather than sending the error message (a string). What do you think? In this way the type would be consistent. Is it possible to make this change?
        3. Moreover, rather then setting the `error` property on the context, wouldn't it be better to set `context.connection.error`, as this is a connection level error? It is cumbersome to check for error at multiple places.
2. It would be beneficial to log the [`error_data` object](https://github.com/amqp/rhea/blob/master/lib/connection.js#L468) as that may contain meaningful information about what happened to the connection. Today this gets lost. I was looking for context.connection.error, whereas the error may have been at context.error. If the error was logged, then at least I could have seen it in the debug logs.
3. I feel the [`Connection.prototype._disconnected()`](https://github.com/amqp/rhea/blob/master/lib/connection.js#L475) method should also ensure that the state of all the sessions, links and the connection object is closed, so that the is_open() method returns the right value. Is that correct? Is that being done currently? If so, then can you explain how does that happen? That will help me better understand the design.

**Comment by grs** [comment]
I have commited some improvements that I believe should address points (1) and (2) above. The error is now passed through on the context to connection_error, connection_close and disconnected. It will always be an error object. In the case of connection_error/connection_close it will be of type rhea.errors.ConnectionError. In the case of disconnected it will be the error from the underlying net.Socket.error event.

On point (3), the state of the connection, sessions and links is separate from the disconnection of the socket. At present they are open unless one of the peers has closed them. Only open links and sessions would be re-established on reconnect. Rather than altering this, I would prefer to add a separate method, e.g. is_active() which would be true if is_open() and not disconnected (to avoid the application having to track this themselves as they would at present). Wdyt?

**Comment by grs** [comment]
I have committed a fix to address (3) also now. Having given it some thought, I agree with you that the is_open() should return false when disconnected. The desired state as used for re-establishing things, should be tracked internally. Let me know what you think.

**Comment by amarzavery** [comment]
Thanks for the quick turn around. Really appreciate that 👍. 
> Let me know what you think.

I like the approach of knowing the state of the endpoint via one method `is_open()` on that entity. This keeps things simple.

I have commented about type definitions and other logical doubts about error handling on the recent commits. Please review them as you find time.

**Comment by amarzavery** [comment]
fixed by https://github.com/amqp/rhea/commit/e2a2c37e3df963ea5b7dedf77439f3e6d5260efb
