### ISSUE TITLE
activemq need connection pool?

### ISSUE THREAD

**Issue by imjuni** [amqp/rhea#314]
Hi there,

I have some question,

I implements code below

```ts
  // AMQPActiveMQ.ts
    this.#queue = this.#container.connect({
      host: this.#config.host.in,
      port: this.#config.port,
      reconnect: this.#config.reconnect,
      transport: this.#config.transport,
      initial_reconnect_delay: this.#config.initialReconnectDelay,
      max_reconnect_delay: this.#config.maxReconnectDelay,
      username: this.#config.username,
      password: this.#config.password,
      container_id: `container-${process.pid}-${uuid.v4().replace(/-/g, '')}`,
    });

  // real usage
  const sender = AMQPActiveMQ.queue.open_sender('same-queue-name');

  const sended = sender.send({
    message_id: uuid.v4().replace(/-/g, ''),
    group_id: 'same-group-id',
    body: msgpack.encode(job),
    ttl: Duration.fromObject({ minute: 5 }).as('milliseconds'),
    application_properties: { AMQ_SCHEDULED_DELAY: 1000 * (isTrue(delaySecond >= 0) ? delaySecond : 0) },
  });
```

Always create new sender for send message. But sometimes ActiveMQ restart caused by unknown reason. I think that non-closed sender. But queue connection only one. 

This is right implementation?  or Need create connection pool?

**Comment by grs** [comment]
Generally I would probably not create a sender for every message. If the reason for creating the sender that way is due to the address not being known up front, you can use the Connection.send()[1] method and  set the address as the 'to' field of every message e.g. https://github.com/amqp/rhea/blob/master/examples/server.js#L30 and https://github.com/amqp/rhea/blob/master/examples/server.js#L26

I'm not sure if I understand your question properly though.

[1] which will create an 'anonymous sender' that does not have a specific target address

**Comment by imjuni** [comment]
@grs Thank you so much!

I reference from https://github.com/amqp/rhea/blob/2cbe55795b86a43375111f2f446089f55b948ecf/examples/simple_send.js#L32

So I miss understand context, I have to create sender object every time.

Thank you.
