### ISSUE TITLE
looks like attach_receiver/attach_sender does not pass the options ahead.

### ISSUE THREAD

**Issue by amarzavery** [amqp/rhea#44]
We are trying to wrap events inside promises. So far the experience has been good. However at one place I was not able pass the options for setting the receiver.

May be I am doing something wrong over here (should be using some other method). Any help/guidance would be awesome.

Here is the [script](https://github.com/amarzavery/rhea/blob/eh/convenience/promises.js#L74).

I want to use the createReceiver() like [this](https://github.com/amarzavery/rhea/blob/eh/convenience/getPart.js#L62), where I can pass in the options along with the endpoint.
```javascript
const rxopt = { name: replyTo, target: { address: replyTo }};
await amqp.createReceiver(session, endpoint, rxopt);
```

Should [this line](https://github.com/grs/rhea/blob/40142ab32feb58ca21f11b3270bacac53bcefea1/lib/session.js#L467) have arguments instead of args.

**Comment by grs** [comment]
The attach_receiver() method on the session (as on the connection) takes only one argument. This may be a string - in which case it is assumed to be the source address - or an object on which the source is a specific field along side other options. The source field itself can be either a string - in which case it is assumed to be the address -  or a nested object containing any of the fields as defined in the AMQP spec.

So in your case (I'm assuming path/endpoint here is the name of the source node to consume from), instead of:

    const receiver = session.attach_receiver(path, options);

you could use:

    var copy = Object.create(options);
    copy.source = path;
    const receiver = session.attach_receiver(copy);
