### ISSUE TITLE
Question on errors during send - events/delivery

### ISSUE THREAD

**Issue by anthonyvercolano** [amqp/rhea#72]
delivery = link.send(message);

I have handlers for error,disconnected, sender_close, accepted, rejected, release, sendable already set up before the call to send.

1) Can those handlers be called before the link.send returns and the context passed as the argument for those handlers be specifically for the message sent in the link.send above?

2) If the answer to 1 is yes, does the delivery returned by the link.send have all the information provided in the context?

3) Should I check if the value of delivery is settled upon return and act "accordingly"?

**Comment by grs** [comment]
All delivery related events will have the specific delivery included in the context. The delivery returned from link.send() is the delivery instance that will be in the context for any events related to that send. The delivery will only be settled on return if you requested that it be sent presettled (through the sender settlement mode), but yes, you should also be able to check the settlement on the returned delivery object.

**Comment by anthonyvercolano** [comment]
The issue that I  am facing is that I create a dictionary with a key of the delivery id found in the delivery returned from link.send.

If the event handler for the link is invoked before the link.send returns then there will not be an entry in the dictionary with that delivery id.  The event handler for the send will look at the context and not be able to find the object in the dictionary keyed by the delivery id.

So, I imagine what I should do, is upon the return from link.send, examine if the delivery is settled. I imagine if I look closely at the delivery object, I can determine which event handler I should invoke?  Then simply invoke that handler and move on?

Is there a definition of the delivery object I can look at and depend on?

**Comment by amarzavery** [comment]
You can take a look y the type definition of Delivery over [here](https://github.com/amqp/rhea/blob/master/typings/session.d.ts#L17).

Use the latest version of rhea. It ships with type definitions.

**Comment by grs** [comment]
The link.send() will not actually write to the socket. That will happen in the next tick. Therefore the handler cannot be invoked before the send has returned and indeed the next tick event is being processed.

However if you are sending settled then the peer will not accept/reject/release etc.

**Comment by anthonyvercolano** [comment]
Ok.  Sorry to re-open.  But just to deal with the fine nuance.

If I set the link to snd_settle_mode  = 1

The link.send will return the delivery marked settled.
There will NOT any event emitted as a result of this send.
Correct?

**Comment by grs** [comment]
> If I set the link to snd_settle_mode = 1
>
> The link.send will return the delivery marked settled.
> There will NOT be any event emitted as a result of this send.
> Correct?

Correct

**Comment by amarzavery** [comment]
@grs - I have a follow up question.
### Is there a relationship between 
 - autoaccept and (rcv_settle_mode and snd_settle_mode) and
- autosettle and (snd_settle_mode and rcv_settle_mode) ?

### What happens if someone sets autoaccept to true and 
  - rcv_settle_mode to 1 or 0
 - snd_settle_mode to 0, 1 or 2 ?
Does one override the other?

**Comment by amarzavery** [comment]
@grs - Any thoughts on this one? Just want to make sure that this follow up question does not get lost in the email notification between the other issue that I filed :).

**Comment by grs** [comment]
rcv_settle_mode and snd_settle_mode are protocol parameters that dictate whether a message needs to be acknowledged, and if so how that acknowledgement works; these allow the delivery semantics to be selected between at-most-once, at-least-once or (assuming correct link recovery) exactly-once

autoaccept and autosettle are parameters controlling what actions the rhea library should perform automatically. autoaccept is used on the receiver side and will result in received messages being automatically accepted (if rcv_settle_mode is 0 they will also be settled). autosettle is used on the sender side and will result in the message being settled automatically once settled by the peer.

If snd_settle_mode is 1 or the rcv_settle_mode of the peer is 1, autosettle is irrelevant. In the first case it is not needed, in the second case the application will need to explicitly settle on accept/release etc.

If autoaccept is set, any messages received unsettled will be accepted. Whether they are settled will depend on the locally specified rcv_settle_mode. If that is 0, they will be settled automatically, if it is 1 then it is the sending peer that needs to settle first, and the application is at present expected to.

rcv_settle_mode=1 is for exactly once, which will usually require manipulating some external/durable state which is why it is at present more explicit (it is also tbh not fully tested).
