### ISSUE TITLE
websockets and x509 - Is it implemented?

### ISSUE THREAD

**Issue by anthonyvercolano** [amqp/rhea#91]
I can connect over websockets.
I can connect using x509 certs.
I don't seem to be able to connect using both.

I'm not seeing (using the debugger) where it is sending the cert down to tls when using websockets.

Thoughts?

**Comment by grs** [comment]
The WebSocket API doesn't provide anyway to pass in client certificates. If connecting from a browser there may be a way to configure the browser with a certificate to use. 

Under node, using the ws module, the thrid argument to the cinnect function returned by rhea.websocket_connect() should be options to pass through (the second argument is the protoocl list as for the WebSocket constructor in the WebSocket API). I think you may be able to specify the client cert (and ca) in those options. (And of course make sure to use wss:// in the url).

**Comment by anthonyvercolano** [comment]
Well that works.

**Comment by OliverSG400** [comment]
Hello guys, could you please share a usage example as a code for this case?
How to specify client certificate in those options?
Thank you in advance for any examples

**Comment by grs** [comment]
It would be something along the lines of:

```
var client = require('rhea');
var WebSocket = require('ws');
var ws = client.websocket_connect(WebSocket);

//....

var opts = {
    key: fs.readFileSync(path.resolve(__dirname,'client-key.pem')),
    cert: fs.readFileSync(path.resolve(__dirname,'client-cert.pem')),
    ca: [ fs.readFileSync(path.resolve(__dirname,'ca-cert.pem')) ]})
};
var connection = client.connect({connection_details:ws("wss://myhost:8080", ["binary", "AMQPWSB10", "amqp"], opts)});
```

**Comment by OliverSG400** [comment]
Thank you a lot for the example! 👍 
As I understand this is for node.js.
May you also share me an example of connecting with client certificate authentication via WebSockets in browser? 
Many thanks

**Comment by grs** [comment]
I don't think there is an api for passing a certificate to a web socket in the browser programmtically. I believe it should work if you install the certificate in your browser and  mark it for use with the url in question.

**Comment by OliverSG400** [comment]
Could you please describe what is "and mark it for use with the URL in question"?
I have successfully tested Rhea with WebSockets client certificate from node.js and installed client certificate into Chrome which works well with nginx client cert check, but I can't make it working with amqp in browser.
Thank you for your help! :)

**Comment by grs** [comment]
what error are you getting?

**Comment by OliverSG400** [comment]
Actually, the reason appeared to be in Chrome official behavior.
Chrome cuts connection, which requires a client certificate. Only for subresource, and only from other domains than the original request. Bu this is exactly my case. One of workaround is to serve both WebSocket + client cert auth, and original https from the same domain.
Firefox works well because they have an auto-fill (browser tries to choose most suitable cert).
Unfortunately Firefox Mobile (for Android) can't work with client certificate so well as the desktop does.

Here is Chrome bug/as designed https://bugs.chromium.org/p/chromium/issues/detail?id=329884

This is not rhea project issue at all, so thank you for the help and thumbs up for your effort on this project!

**Comment by OliverSG400** [comment]
and here is the error itself 
Chrome failing to connect to websocket server (Opcode -1) “handshake was canceled”
